### ISSUE TITLE
measureText не верно рассчитывает ширину текста

### ISSUE THREAD

**Issue by FireVolkhov** [theshock/libcanvas#59]
measureText не верно рассчитывает ширину текста.
Тут скорее всего должна вызываться функция `apply` вместо `call`
https://github.com/theshock/libcanvas/blob/master/Source/Context/Text.js#L61
http://i.imgur.com/LznJLJA.png

**Comment by theshock** [comment]
Да, ты прав) Кинешь пул-реквест, а я вмерджу?

**Comment by FireVolkhov** [comment]
Ок, кину

**Comment by svtux** [comment]
Неплохо бы закрыть вопрос. Решен.
